feat: add friendly tips in the development env when developer uses as…
alibaba/rax pull request #1447
Opened 2019-10-27 03:34 UTC by evilbs

1. add friendly tips in the development env when the developer uses async in effect.

2019-10-27 03:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/rax?pullRequest=1447) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/rax?pullRequest=1447) before we can accept your contribution.<br/><hr/>**易国勇** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/rax?pullRequest=1447) it.</sub>

2019-10-27 04:07 UTC, andycall approved these changes

2019-10-27 04:07 UTC, andycall commented on packages/rax/src/hooks.js
> +                'Learn more about data fetching with Hooks: https://fb.me/react-hooks-data-fetching';
这里得把facebook的地址去掉

2019-10-27 04:08 UTC, andycall commented
fixed #1389

2019-10-27 04:29 UTC, evilbs commented on packages/rax/src/hooks.js
> +                'Learn more about data fetching with Hooks: https://fb.me/react-hooks-data-fetching';
我也是这样考虑，rax 有地方可以放这个说明吗？

2019-10-27 04:30 UTC, andycall commented on packages/rax/src/hooks.js
> +                'Learn more about data fetching with Hooks: https://fb.me/react-hooks-data-fetching';
现在还没这样的一个网站。。或许未来可以做一个 @yuanyan

2019-10-27 05:07 UTC, evilbs commented on packages/rax/src/hooks.js
> +                'Learn more about data fetching with Hooks: https://fb.me/react-hooks-data-fetching';
我感觉要自己做一个网站，方便 rax 的社区朋友，需要是同样的 api，但一些差异和新功能都可以在上面说明。类似于 preact:https://preactjs.com/guide/v10/hooks

2019-10-27 10:35 UTC, yuanyan commented on packages/rax/src/hooks.js
> +          const { current } = __destory;
current 在一个 scope 定义了两次

2019-10-27 10:38 UTC, yuanyan commented on packages/rax/src/hooks.js
> +          const { current } = __destory;
不知道为什么 lint 没有检查出来

2019-10-27 10:38 UTC, yuanyan requested changes
变量命名优化

2019-10-27 13:00 UTC, evilbs commented on packages/rax/src/hooks.js
> +          const { current } = __destory;
因为第二个 current 是在 if 块线作用域里，并不会冲突。

```javascript
const a= 10;
if (true) {
   const a = 'inner'; 
}
```

会转换成 如下 es5 代码 ===>
```javascript
var a = 10;

if (true) {
  var _a = 'inner';
}
```

2019-10-27 13:10 UTC, evilbs commented on packages/rax/src/hooks.js
> +          const { current } = __destory;
不过我感觉在可读性上很容易让别人感觉代码不可靠，所以我还是修改一下。

2019-10-28 02:22 UTC, evilbs commented
@yuanyan 搞定了，合并一下吧

2019-10-28 04:22 UTC, yuanyan commented on packages/rax/src/hooks.js
> +          const destoryCurrent = __destory.current;
destoryCurrent -> currentDestory

2019-10-28 05:17 UTC, evilbs commented on packages/rax/src/hooks.js
> +          const destoryCurrent = __destory.current;
好

2019-10-28 05:47 UTC, yuanyan approved these changes

2019-10-28 05:48 UTC, merged